---

- name: Installation et configuration de NGINX
  hosts: webservers
  become: true
  tasks:
    - name: Installation de NGINX
      package: name=nginx update_cache=yes

    - name: Copie des fichiers de configuration NGINX
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default

    - name: Activer la configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: Copie de la page web index.html
      template: >
        src=index.html.j2
        dest=/usr/share/nginx/html/index.html

    - name: Redémarrage de NGINX pour appliquer la configuration
      service: name=nginx state=restarted

...